embed = new Discord.MessageEmbed()
    .setTitle("きりたんbotのグロチャ一覧ですよ")
    .setAuthor("きりたんbotでつかえるグロチャ")
    .setColor(0x00AE86)
    .addField('kiritan-global', 'メイングロチャ')
    .addField('jinro-game-audience', 'サブグロチャ(旧人狼ゲーム観戦用チャット)')
    .setThumbnail("https://yagami.xyz/content/uploads/2018/11/discord-512-1.png")
    .setTimestamp()
message.channel.send(embed)